### ISSUE TITLE
The  version r70 and r87 is not working on rmbp 2018.

### ISSUE THREAD

**Issue by wthe2004** [NoaHimesaka1873/tiny-dfr-arch#1]
The  version r70 and r87 is not working on rmbp 2018. I am  the version r45 before now.
The touchbar is blank, and the error message is:
```sh
thread 'main' panicked at src/main.rs:381:43:
called `Result::unwrap()` on an `Err` value: No touchbar device found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by NoaHimesaka1873** [comment]
Likely new kernel issue. Wait for new kernel release. If this happens after 6.9.2 release, open the issue again.
